#!/usr/bin/env python3
"""Validate a reviewer verdict and render the sticky PR comment (stdlib only).

Usage: verdict.py --tool NAME --mode gate|advisory --marker MARKER --head SHA RAW_FILE
Stdout: comment body. Exit: 0 pass; 1 blocking findings (gate mode only);
3 unparseable/invalid verdict (gate callers must fail closed).
Advisory mode never returns 1: findings are posted, the check stays green.
Rendered text is neutralised (no @-mentions, HTML or code fences from model output).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from typing import Any

MAX_ITEMS = 25
SEVERITIES = ("critical", "high")


def _extract(raw: str) -> Any:
    raw = raw.strip()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass
    # stream-json (kimi): last assistant message with string content.
    for line in reversed(raw.splitlines()):
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(event, dict) and event.get("role") == "assistant" and isinstance(event.get("content"), str):
            try:
                return json.loads(event["content"].strip())
            except json.JSONDecodeError:
                return None
    start, end = raw.find("{"), raw.rfind("}")
    if 0 <= start < end:
        try:
            return json.loads(raw[start:end + 1])
        except json.JSONDecodeError:
            return None
    return None


def validate(data: Any) -> dict[str, Any]:
    if not isinstance(data, dict) or data.get("verdict") not in ("pass", "changes"):
        raise ValueError("verdict must be pass or changes")
    if not isinstance(data.get("summary"), str):
        raise ValueError("summary must be a string")
    for key in ("blockers", "notes"):
        if not isinstance(data.get(key), list):
            raise ValueError(f"{key} must be a list")
    for item in data["blockers"]:
        if (not isinstance(item, dict) or not isinstance(item.get("file"), str)
                or item.get("severity") not in SEVERITIES or not isinstance(item.get("why"), str)):
            raise ValueError("invalid blocker entry")
    for item in data["notes"]:
        if not isinstance(item, dict) or not isinstance(item.get("file"), str) or not isinstance(item.get("note"), str):
            raise ValueError("invalid note entry")
    if data["verdict"] == "changes" and not data["blockers"]:
        raise ValueError("verdict 'changes' requires at least one blocker")
    if data["verdict"] == "pass" and data["blockers"]:
        raise ValueError("verdict 'pass' cannot carry blockers")
    return data


def safe(text: Any, limit: int = 1200) -> str:
    value = re.sub(r"[\r\n]+", " ", str(text))[:limit]
    return value.replace("@", "＠").replace("<", "‹").replace("`", "´")


def _where(item: dict[str, Any]) -> str:
    line = item.get("line")
    return safe(item["file"], 240) + (f":{safe(line, 20)}" if line not in (None, "") else "")


def render(tool: str, mode: str, marker: str, head: str, data: dict[str, Any]) -> str:
    blocking = data["verdict"] == "changes"
    if mode == "gate":
        title = (f"## {tool} review: changes requested ({len(data['blockers'])} blocking)"
                 if blocking else f"## {tool} review: pass")
    else:
        title = f"## {tool} advisory review: {'findings' if blocking else 'pass'}"
    lines = [marker, title, "", f"Reviewed head: `{head}`", "", safe(data["summary"])]
    if data["blockers"]:
        lines += ["", "### Blocking" if mode == "gate" else "### Findings"]
        lines += [f"- **{item['severity']}** {_where(item)} — {safe(item['why'])}"
                  for item in data["blockers"][:MAX_ITEMS]]
    if data["notes"]:
        lines += ["", "### Notes (non-blocking)"]
        lines += [f"- {_where(item)} — {safe(item['note'], 800)}" for item in data["notes"][:MAX_ITEMS]]
    footer = ("critical/high findings fail this check; push a fix to trigger a fresh review."
              if mode == "gate" else "Advisory only: this check never blocks merge.")
    lines += ["", f"<sub>Generated by the local {safe(tool, 40)} CLI. {footer} "
                  "A new push invalidates this review.</sub>"]
    return "\n".join(lines) + "\n"


def unavailable(tool: str, mode: str, marker: str, head: str, reason: str) -> str:
    consequence = ("For safety this check fails until a review completes; re-run the job."
                   if mode == "gate" else "Advisory only: this check does not block merge.")
    return f"{marker}\n## {tool} review unavailable\n\nReviewed head: `{head}`\n\n{safe(reason)}\n\n{consequence}\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="verdict")
    parser.add_argument("--tool", required=True)
    parser.add_argument("--mode", choices=("gate", "advisory"), required=True)
    parser.add_argument("--marker", required=True)
    parser.add_argument("--head", required=True)
    parser.add_argument("--unavailable", help="render an unavailable notice with this reason")
    parser.add_argument("raw", nargs="?")
    args = parser.parse_args(argv)
    if args.unavailable is not None:
        sys.stdout.write(unavailable(args.tool, args.mode, args.marker, args.head, args.unavailable))
        return 0 if args.mode == "advisory" else 3
    try:
        with open(args.raw, encoding="utf-8", errors="replace") as handle:
            data = validate(_extract(handle.read()))
    except (OSError, TypeError, ValueError) as error:
        sys.stdout.write(unavailable(args.tool, args.mode, args.marker, args.head,
                                     f"The reviewer returned an invalid verdict ({error})."))
        return 0 if args.mode == "advisory" else 3
    sys.stdout.write(render(args.tool, args.mode, args.marker, args.head, data))
    if args.mode == "gate" and data["verdict"] == "changes":
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
